[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"
authors = ["noruffle"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "src"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
